# .air.toml — Development live reload configuration for Air

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "tmp/api"
  include_ext = ["go", "mod", "sum"]
  exclude_dir = ["tmp", "vendor", "coverage", ".git", ".idea", ".vscode"]
  delay = 200 # milliseconds
  stop_on_error = true

[log]
  time = true
  color = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[env]
  PORT = "8080"
  LOG_LEVEL = "DEBUG"
